# 30 core terms: (label, zh, glossary id, text with KaTeX)
CHEAT = [
 ("Autoregressive language model", "自回归", "gl-autoregressive", "\\(p(x_{1:T})=\\prod_t p(x_t\\mid x_{&lt;t})\\); trained with mean next-token cross-entropy; perplexity \\(=e^{\\text{loss}}\\), per token, so not comparable across tokenizers."),
 ("BPE tokenizer", "字节对编码", "gl-byte-pair-encoding", "merge the most frequent adjacent pair; byte-level BPE starts from the 256 bytes, so there is no unknown token."),
 ("Attention and causal mask", "因果掩码", "gl-causal-mask", "\\(\\softmax(QK^\\top/\\sqrt{d_h} + M)V\\) with \\(M = -\\infty\\) above the diagonal; \\(O(T^2)\\) compute; heads work in separate subspaces."),
 ("Modern block", "预归一化", "gl-pre-ln", "Pre-LN, RMSNorm and a SwiGLU FFN; the FFN holds about 70% of Llama-3-8B's parameters."),
 ("RoPE", "旋转位置编码", "gl-rotary-position-embedding", "rotate each (q, k) pair by \\(t\\theta_i\\), \\(\\theta_i = b^{-2i/d_h}\\); the score \\(q_t\\cdot k_j\\) depends only on \\(t-j\\)."),
 ("KV cache", "键值缓存", "gl-kv-cache", "\\(2\\,n_{kv}d_hL\\) elements per token; Llama-3-8B in bf16 is 128 KiB per token, 1 GiB at 8K."),
 ("Prefill and decode", "预填充", "gl-prefill", "prefill is parallel over the prompt and compute-bound; decode reads all weights and the cache every step and is memory-bound."),
 ("Roofline", "屋顶线模型", "gl-roofline-model", "attainable FLOP/s \\(=\\min(P,\\, I\\beta)\\); the H100 ridge is \\(989.4/3.35 \\approx 295\\) FLOPs per byte."),
 ("MFU", "模型浮点运算利用率", "gl-model-flops-utilization", "observed model FLOP/s over the dense peak (989 TFLOP/s bf16 on an H100; 1,979 assumes sparsity); training costs about \\(6N\\) FLOPs per token."),
 ("GQA", "分组查询注意力", "gl-grouped-query-attention", "\\(n_{kv}\\) shared KV heads, cache smaller by \\(n_h/n_{kv}\\) (4× for Llama-3-8B); MQA is \\(n_{kv}=1\\)."),
 ("MLA", "多头潜在注意力", "gl-multi-head-latent-attention", "cache one latent plus a decoupled-RoPE key: \\(512 + 64 = 576\\) elements per layer in DeepSeek-V3 (68.6 KiB per token)."),
 ("MoE and activated parameters", "混合专家", "gl-mixture-of-experts", "\\(C \\approx 6N_{\\text{act}}D\\) but memory follows the total \\(N\\); DeepSeek-V3: 671B total, 37B activated."),
 ("Load balancing", "负载均衡", "gl-load-balancing", "auxiliary loss \\(\\alpha\\, n_r \\sum_i f_iP_i\\), or a per-expert routing bias with no auxiliary loss (V3); failure modes: collapse, stragglers, overflow."),
 ("Sliding-window and sparse attention", "稀疏注意力", "gl-sparse-attention", "cost \\(O(TW)\\) or \\(O(Tk)\\) instead of \\(O(T^2)\\); \\(\\ell\\) sliding-window layers reach about \\(\\ell(W-1)\\) tokens back."),
 ("Linear attention and hybrids", "线性注意力", "gl-linear-attention", "fixed \\(d_k \\times d_v\\) state per head; a constant state cannot recall \\(N\\) items exactly, so hybrids keep a few softmax layers (3:1 in Qwen3-Next)."),
 ("Position interpolation and YaRN", "位置插值", "gl-position-interpolation", "PI divides positions by \\(s\\); YaRN keeps high-frequency pairs, interpolates low-frequency ones and adds a logit temperature \\((0.1\\ln s + 1)^2\\)."),
 ("Scaling laws", "缩放定律", "gl-scaling-laws", "\\(C \\approx 6ND\\); compute-optimal is about 20 tokens per parameter; over-train small models (Llama 3 8B: 15T tokens) to cut serving cost."),
 ("Optimizer and schedule", "优化器", "gl-optimizer", "AdamW with warmup, a hold and a decay; batch size counted in tokens and limited by the critical batch size."),
 ("Mixed precision", "混合精度训练", "gl-mixed-precision-training", "bf16 weights and gradients plus an fp32 master copy and two Adam moments: \\(2 + 2 + 12 = 16\\) bytes per parameter."),
 ("ZeRO and FSDP", "零冗余优化器", "gl-zero", "shard optimizer states (stage 1), gradients (2), parameters (3): \\(16N/N_d\\) bytes per GPU at stage 3, about 1.5× the communication of plain DP."),
 ("Parallelism", "张量并行", "gl-tensor-parallelism", "tensor parallelism inside a node (all-reduce per layer), pipeline across nodes (bubble \\((p-1)/m\\) of ideal time), expert (all-to-all), context (long sequences), data (replicas)."),
 ("FlashAttention", "算子融合", "gl-kernel-fusion", "tile \\(Q, K, V\\) in SRAM with online softmax: exact, never writes the \\(T \\times T\\) matrix to HBM, recomputes tiles in the backward pass."),
 ("Speculative decoding", "投机解码", "gl-speculative-decoding", "draft \\(\\gamma\\) tokens with a cheap \\(q\\), verify \\(\\gamma+1\\) in one target pass; the output distribution is exactly \\(p\\)."),
 ("Quantization", "量化", "gl-quantization", "named WxAy plus a KV format; PTQ converts a trained model, QAT trains with the quantizer; block scales cost bits (MXFP4: 4.25 per element)."),
 ("SFT", "监督微调", "gl-supervised-fine-tuning", "cross-entropy on response tokens only, in a chat template; behavior cloning, so it cannot say one answer beats another."),
 ("LoRA", "低秩适配", "gl-low-rank-adaptation", "\\(W_0 + \\tfrac{\\alpha}{r}BA\\), mergeable so serving is free; QLoRA adds an NF4 base and double quantization."),
 ("Reward model", "奖励模型", "gl-reward-model", "Bradley-Terry: \\(P(y_1 \\succ y_2) = \\sigma(r_1 - r_2)\\); optimizing it hard causes over-optimization (Goodhart's law)."),
 ("PPO and RLHF", "近端策略优化", "gl-proximal-policy-optimization", "maximize \\(\\min(\\rho A,\\ \\operatorname{clip}(\\rho, 1\\pm\\epsilon)A)\\) with a KL penalty; four models in memory (policy, reference, reward, critic)."),
 ("DPO", "直接偏好优化", "gl-direct-preference-optimization", "\\(-\\log\\sigma\\big(\\beta[\\log\\tfrac{\\pi_\\theta(y_w)}{\\pi_{\\text{ref}}(y_w)} - \\log\\tfrac{\\pi_\\theta(y_l)}{\\pi_{\\text{ref}}(y_l)}]\\big)\\); \\(Z(x)\\) cancels."),
 ("GRPO and RLVR", "组相对策略优化", "gl-group-relative-policy-optimization", "group-mean baseline and no critic, with a program as the reward; watch for entropy collapse (DAPO's four fixes)."),
]
assert len(CHEAT) == 30
