# Glossary data for page 37: merge map, cleaned English terms and one-line definitions.
# Keys are the exact span.zh strings from refs.json. Definitions follow the wording of the page where the term is defined.

# variant -> canonical (one standard mainland term per concept)
MERGE = {
    "对话模板": "聊天模板",
    "排列等变性": "置换等变性",
    "外推": "长度外推",
    "插值": "位置插值",
    "内存带宽": "显存带宽",
    "计算强度": "算术强度",
    "重计算": "激活重计算",
    "多 token 预测": "多词元预测",
    "推测解码": "投机解码",
    "投机采样": "投机解码",
    "蒸馏": "知识蒸馏",
    "涌现": "涌现能力",
    "混合推理架构": "混合推理",
    "滑动窗口": "滑动窗口注意力",
    "细粒度专家": "细粒度专家分割",
    "人类反馈强化学习": "基于人类反馈的强化学习",
}

# canonical zh -> (English term, definition)
G = {
# ---- Part I
"语言模型": ("language model", "A probability distribution over sequences of tokens, factored by the chain rule into next-token conditionals."),
"词元": ("token", "A subword unit from a fixed vocabulary of V entries (typically 32K to 256K); the symbol a language model predicts."),
"自回归": ("autoregressive", "Representing every conditional p(x_t | x_<t) with one shared network that reads a prefix and returns a logit per vocabulary entry; generation repeats this one token at a time."),
"掩码语言模型": ("masked language modeling (MLM)", "BERT-style objective: hide some tokens and predict them from context on both sides."),
"最大似然估计": ("maximum likelihood estimation (MLE)", "Choose the parameters that make the training data most probable; with logs and averaging it becomes next-token cross-entropy."),
"教师强制": ("teacher forcing", "Feeding the ground-truth token, never the model's own sample, as input at each position in training, so all T conditionals are computed in one parallel pass."),
"曝光偏差": ("exposure bias", "The mismatch created by teacher forcing: training prefixes come from the data, generation prefixes from the model, so errors can accumulate."),
"困惑度": ("perplexity", "The exponential of the mean per-token loss (in nats); the effective number of equally likely next tokens."),
"仅解码器架构": ("decoder-only architecture", "One causal Transformer stack trained on next-token prediction (GPT-2 and GPT-3, Llama 3, DeepSeek-V3), with no encoder or cross-attention."),
"预训练": ("pretraining", "Next-token cross-entropy on trillions of tokens of web text, code, books and math; produces the base model and uses nearly all of the compute."),
"基座模型": ("base model", "The checkpoint that pretraining produces: it continues text but has not been tuned to follow instructions."),
"监督微调": ("supervised fine-tuning (SFT)", "Continue training with cross-entropy on (prompt, response) pairs rendered in a chat template, with loss on the response tokens only."),
"基于人类反馈的强化学习": ("reinforcement learning from human feedback (RLHF)", "Collect human comparisons, train a reward model, then optimize the policy against it (PPO with a KL penalty in InstructGPT)."),
"上下文学习": ("in-context learning (ICL)", "Doing a new task from instructions or a few demonstrations in the prompt with no weight update (zero-, one- and few-shot)."),
"涌现能力": ("emergent abilities", "Abilities absent in smaller models and present in larger ones, so not predictable by extrapolation (Wei et al.); Schaeffer et al. argue many sharp jumps come from the metric."),
"分词器": ("tokenizer", "The component that maps a string to integer token ids (and back) using a fixed vocabulary."),
"词表": ("vocabulary", "The set of all tokens, of size V; it fixes the V·d embedding table and the V-way softmax."),
"子词": ("subword", "A unit between characters and words: keeps sequences short without an unbounded vocabulary."),
"字节对编码": ("byte-pair encoding (BPE)", "Start from characters (or bytes) and repeatedly merge the most frequent adjacent pair; the number of merges is the only hyperparameter."),
"字节级 BPE": ("byte-level BPE", "BPE over the 256 UTF-8 bytes, so any string is representable and there is no unknown token (GPT-2: 256 bytes + 50,000 merges + 1 special token = 50,257)."),
"预分词": ("pre-tokenization", "A regex that cuts text into pre-tokens before BPE so that merges do not cross character categories (except spaces); BPE runs inside each pre-token."),
"一元语言模型": ("Unigram language model (tokenizer)", "Kudo's tokenizer: start from a large seed vocabulary and prune top-down by likelihood; the best segmentation is a Viterbi path and segmentations can also be sampled."),
"子词正则化": ("subword regularization", "Training on segmentations sampled from a probabilistic tokenizer (BPE-dropout is the BPE counterpart); worth about +1 to 2 BLEU on most translation pairs."),
"权重共享": ("weight tying", "Sharing the input embedding with the output (unembedding) matrix, so its V·d parameters are counted once."),
"特殊词元": ("special tokens", "Vocabulary entries added by hand (end of document, role headers, end of turn); matched as literal strings before pre-tokenization."),
"聊天模板": ("chat template", "The rule that serializes role-tagged messages into one token sequence with special tokens; rendered in full for training, and up to the assistant header for inference."),
"注意力机制": ("attention", "A differentiable dictionary lookup: a query is compared with every key, the scores become softmax weights, and the output is the weighted average of the values."),
"查询、键、值": ("query, key, value (QKV)", "The three roles in attention: the query says what a position looks for, the key what it advertises, the value what it hands over when selected."),
"自注意力": ("self-attention", "Attention whose queries, keys and values are all linear projections of the same sequence."),
"缩放点积注意力": ("scaled dot-product attention", "Attn(Q, K, V) = softmax(QKᵀ/√d_h) V, the attention of Vaswani et al. (Eq. 1)."),
"交叉注意力": ("cross-attention", "Queries come from one sequence and keys and values from another (the encoder output in the original Transformer), with no causal mask."),
"温度": ("temperature", "A divisor applied to logits before a softmax: fixed at √d_h inside attention (page 03), and a tunable τ in sampling that sharpens or flattens the distribution (page 06)."),
"因果掩码": ("causal mask", "A matrix added to the attention logits (minus infinity above the diagonal) so that position t cannot read positions after it."),
"多头注意力": ("multi-head attention (MHA)", "Runs n_h attentions in parallel in low-dimensional subspaces, each with its own softmax, and concatenates the results."),
"低秩瓶颈": ("low-rank bottleneck", "With d fixed, more heads means smaller d_h, and each head's logit matrix has rank at most d_h: a proposed explanation for quality dropping at very many heads."),
"置换等变性": ("permutation equivariance", "Permuting the input rows permutes the output rows the same way, f(ΠX) = Πf(X); unmasked self-attention without positional information has it."),
"归纳头": ("induction head", "An attention head that completes [A][B] ... [A] → [B]: it finds an earlier copy of the current token and copies the token that followed it."),
"残差连接": ("residual connection", "Adding a sublayer's output to its input, x + F(x); each attention and MLP sublayer is wrapped in one."),
"前馈网络": ("feed-forward network (FFN)", "The position-wise MLP in each block: the same function with the same weights applied to every token independently."),
"残差流": ("residual stream", "The vector each token carries through the network; every sublayer reads from it and writes to it by addition."),
"后归一化": ("Post-LN", "The original Transformer's norm placement: normalize after the residual addition."),
"预归一化": ("Pre-LN", "Normalize the input of each sublayer, plus one extra norm after the last block; the modern default."),
"层归一化": ("LayerNorm", "Subtract the mean and divide by the standard deviation over the feature axis, then apply a learned gain and bias."),
"均方根归一化": ("RMSNorm", "LayerNorm keeping only the rescaling: divide by the root mean square and apply a learned gain."),
"门控线性单元": ("gated linear unit (GLU)", "Multiplies two linear projections of the input elementwise, one passed through an activation; with SiLU it is SwiGLU."),
"词嵌入": ("token embedding", "The V×d table that turns each token id into a row: a gather with V·d parameters and no FLOPs."),
"模型浮点运算利用率": ("model FLOPs utilization (MFU)", "Observed model-FLOP throughput divided by the hardware's dense peak (Llama 3 405B: 430 TFLOP/s per GPU, 43%)."),
"激活值": ("activations", "Tensors saved in the forward pass for the backward pass (matmul inputs, norm inputs, FFN intermediates); their memory scales with tokens in flight × layers × width."),
"位置编码": ("positional encoding", "Order information injected into the model; without it attention, norms and FFNs cannot tell \"dog bites man\" from \"man bites dog\"."),
"绝对位置编码": ("absolute positional encoding", "Gives each index its own vector, added to the token embedding (fixed sinusoidal in the original Transformer, or learned)."),
"相对位置编码": ("relative positional encoding", "An encoding that depends on the offset between query and key rather than on absolute indices (Shaw et al.: a learned vector per clipped offset)."),
"旋转位置编码": ("rotary position embedding (RoPE)", "Rotates each query and key pair of dimensions by a position-dependent angle so the dot product depends only on the offset; the scheme of most open models."),
"长度外推": ("length extrapolation", "Running a model on inputs longer than any it trained on; RoPE models fail at it for two separable reasons (unseen angles, attention dilution)."),
"位置插值": ("position interpolation", "Squeezing a longer position range into the range the model has seen, instead of extrapolating beyond it."),
"解码": ("decoding", "The autoregressive generation loop: pick a token from the model's distribution, append it, repeat."),
"采样": ("sampling", "Picking a token from the model's distribution; greedy selection is its deterministic special case."),
"预填充": ("prefill", "One forward pass over all P prompt tokens at once, parallel over positions; it also stores every layer's keys and values."),
"键值缓存": ("KV cache", "The stored keys and values of all earlier tokens in every layer, so each decode step computes only the new token; memory grows linearly with context."),
"核采样": ("nucleus sampling (top-p)", "Keep the smallest set of top tokens whose total probability is at least p, renormalize, and sample from it."),
"束搜索": ("beam search", "Deterministic search that keeps b partial hypotheses, expands each by all V tokens and keeps the best b by cumulative log-probability."),
"算术强度": ("arithmetic intensity", "FLOPs performed per byte moved from memory; compared with the hardware ridge point (about 295 FLOPs per byte on an H100 SXM) to tell memory-bound from compute-bound."),
"访存受限": ("memory-bound", "A kernel below the ridge point: its time is set by bytes moved, not FLOPs (decode is the standard example)."),
"计算受限": ("compute-bound", "A kernel above the ridge point: its time is set by FLOPs."),
"首 token 延迟": ("time to first token (TTFT)", "Latency from request arrival to the first output token, including queueing, prefill and network."),
"连续批处理": ("continuous batching", "Scheduling per model iteration: finished sequences leave and waiting requests join at every step, so short requests do not wait on a static batch's longest one (Orca)."),
"前缀缓存": ("prefix caching", "Requests that share a prefix (system prompt, few-shot examples, earlier turns) reuse the same KV-cache entries and skip that part of prefill."),
"显存带宽": ("memory bandwidth (HBM)", "The rate at which data streams from GPU memory to the compute units (H100 SXM: 3.35 TB/s); decode is limited by it because every step reads the weights and the whole KV cache."),
"多查询注意力": ("multi-query attention (MQA)", "Keeps n_h query heads but a single key head and a single value head shared by all of them."),
"分组查询注意力": ("grouped-query attention (GQA)", "Splits the n_h query heads into n_kv groups that each share one key head and one value head; GQA-n_h is MHA and GQA-1 is MQA."),
"张量并行": ("tensor parallelism (TP)", "Splits each layer's matrices (and attention heads) across GPUs, with all-reduces inside every layer; used within a node, typically 8-way."),
"多头潜在注意力": ("multi-head latent attention (MLA)", "DeepSeek-V2's attention: cache one low-rank latent per token (plus a small decoupled-RoPE key) and up-project it to keys and values."),
"低秩压缩": ("low-rank compression", "Factoring a large projection through a small rank r; in MLA the stacked K/V projection is factored through rank 512."),
"权重吸收": ("weight absorption", "Folding MLA's key up-projection into the query side and its value up-projection into the output side, so attention runs directly on the cached latents."),
# ---- Part II
"混合专家": ("mixture of experts (MoE)", "Replaces the FFN sublayer with many expert FFNs plus a router that picks k per token: parameters grow with the expert count, FLOPs follow the activated ones."),
"路由": ("router (routing)", "The small network that scores the experts for each token and picks the top-k routed experts."),
"激活参数": ("activated parameters", "The parameters touched by one token's forward pass, N_act; training compute is about 6·N_act·D (DeepSeek-V3: 37B of 671B)."),
"稀疏度": ("sparsity (MoE)", "Total routed experts per activated routed expert, n_r/k (Kimi K2's definition: 384/8 = 48; V3 has 32)."),
"共享专家": ("shared expert", "An expert FFN that every token uses with gate 1, capturing common knowledge so the routed experts can specialize."),
"负载均衡": ("load balancing", "Making every expert receive a similar number of tokens, to avoid routing collapse, stragglers under expert parallelism and buffer overflow."),
"路由坍塌": ("routing collapse", "The router converging to a few favored experts, self-reinforcing because favored experts train faster."),
"容量因子": ("capacity factor", "The multiplier on the average expert load that sets each expert's fixed buffer, C = ⌈cf·T·k/n_r⌉; assignments beyond it are dropped."),
"无辅助损失负载均衡": ("auxiliary-loss-free load balancing", "Takes the balance term out of the gradient: a per-expert bias, used only to choose the top-k, is adjusted by a controller toward balance (Wang et al.; DeepSeek-V3 moves it by a fixed step, Kimi K3's Quantile Balancing sets it from router-score quantiles, page 32)."),
"细粒度专家分割": ("fine-grained expert segmentation", "Split each expert's hidden width into m pieces and activate mK instead of K: same parameters and FLOPs, many more expert combinations."),
"专家并行": ("expert parallelism (EP)", "Shards the experts of every MoE layer across devices with all-to-all token dispatch and combine, while attention runs data-parallel."),
"滑动窗口注意力": ("sliding-window attention (SWA)", "Each query attends only to the W most recent keys: cost O(n·W), and ℓ stacked layers give a receptive field of about ℓ(W−1)."),
"感受野": ("receptive field", "How far back the top layer can depend on the input: about ℓ(W−1) positions for ℓ sliding-window layers (Mistral 7B: 32 × 4096 ≈ 131K)."),
"稀疏注意力": ("sparse attention", "Each query attends to a small subset of keys chosen by content, so per-query compute is O(k) instead of O(T)."),
"线性注意力": ("linear attention", "Replaces exp(q·k) by a factorizable kernel φ(q)φ(k)ᵀ, so attention becomes a recurrence with a fixed-size state."),
"联想记忆": ("associative memory", "The fixed-size state of linear attention (d_k × d_v numbers per head), independent of sequence length."),
"状态空间模型": ("state-space model (SSM)", "Recurrent layers from control theory (S4, Mamba, Mamba-2) with a fixed-size state; Mamba makes the parameters depend on the input."),
"混合架构": ("hybrid architecture", "Mixes a few softmax-attention layers with many linear-attention or SSM layers, so the exact-recall gap of a constant state is repaired."),
"联想召回": ("associative recall", "Answering \"what followed this key last time?\" from context (lookups, copying); any causal recurrent model needs Ω(N) bits of state to solve it over N tokens."),
"大海捞针": ("needle in a haystack (NIAH)", "A long-context test that hides one fact in filler text and asks for it; near-perfect scores hide failures on harder tasks (RULER)."),
"长上下文": ("long context", "A context window of 128K to 1M tokens, almost never trained at that length from the first step."),
"上下文窗口": ("context window", "The maximum number of tokens a model accepts in one sequence."),
"继续预训练": ("continued pretraining", "Further pretraining of an existing checkpoint with the same next-token loss; for long context, pretrain short for almost all tokens, then continue at longer lengths on a small fraction of the budget (Llama 3: about 800B of 15.6T tokens)."),
"上下文并行": ("context parallelism (CP)", "Shards one sequence across GPUs (Llama 3: 2×CP chunks per sequence, K and V all-gathered), balancing the causal mask's uneven work."),
"环形注意力": ("Ring Attention", "Passes KV blocks around a ring of devices while each computes on its current block, hiding the transfer behind compute."),
"分块预填充": ("chunked prefill", "Processes a long prompt in chunks that each attend to the cache built so far, bounding activation memory and letting decode requests interleave."),
"有效上下文长度": ("effective context length", "RULER's headline measure: the largest tested length at which the average score still exceeds a fixed pass mark."),
"训练稳定性": ("training stability", "A run keeps making progress at the chosen learning rate; it fails as loss spikes, slow divergence or slow drift."),
"损失尖峰": ("loss spike", "A sudden jump of the training loss, followed by recovery or divergence."),
"梯度裁剪": ("gradient clipping", "Rescaling the gradient when its norm exceeds a threshold; it does not prevent every spike (PaLM 540B spiked about 20 times despite it)."),
"学习率预热": ("learning-rate warmup", "Ramping the learning rate from near zero to its peak over the first steps; a longer warmup is a stability lever."),
"权重衰减": ("weight decay", "Shrinking the weights a little each step (the term λθ, decoupled from the gradient in AdamW); in one-pass pretraining it aids optimization and stability rather than fighting overfitting."),
"超连接": ("hyper-connections (HC)", "Widen the residual stream into n parallel streams with learned mixing."),
"流形约束超连接": ("manifold-constrained hyper-connections (mHC)", "Hyper-connections whose residual mixing matrix is constrained to be doubly stochastic, which keeps them stable at scale (DeepSeek-V4, n = 4)."),
"双随机矩阵": ("doubly stochastic matrix", "A non-negative matrix whose rows and columns each sum to 1 (the Birkhoff polytope); products of such matrices stay doubly stochastic."),
"多词元预测": ("multi-token prediction (MTP)", "Adds losses that also predict x_{t+2}, ... as auxiliary targets; DeepSeek-V3's second-token acceptance of 85% to 90% makes it a free draft for speculative decoding."),
# ---- Part III
"预训练数据": ("pretraining data", "A mixture of domains (web text from Common Crawl, code, math, books, papers, multilingual text) that the pipeline filters and weights."),
"数据清洗": ("data cleaning", "The stage of the web pipeline that orders filters by cost (URL, language, heuristics, deduplication, model-based scoring), each threshold justified by an ablation."),
"语言识别": ("language identification", "A fastText classifier over character n-grams that labels each document's language, with per-language score cutoffs."),
"去重": ("deduplication", "Removing exact and near-duplicate documents; it cuts memorized output about 10× (1.9% to 0.19% of generated tokens) and saves up to 19% of training tokens at the same or better accuracy (Lee et al.)."),
"最小哈希": ("MinHash", "A signature whose agreement rate between two documents estimates their Jaccard similarity J."),
"局部敏感哈希": ("locality-sensitive hashing (LSH)", "Split MinHash signatures into b bands of r rows so that similar documents collide in some bucket, avoiding O(N²) pair comparisons."),
"质量过滤": ("quality filtering", "Train a classifier to score every document, then keep the top fraction or upsample by score."),
"数据配比": ("data mixture", "The vector of sampling weights over domains; a weight is not a corpus share, since small high-quality domains are repeated."),
"退火": ("annealing (data)", "Switching to a smaller, cleaner, more task-like data mix in the last few percent of training, while the learning rate decays (Meta's term)."),
"中期训练": ("mid-training", "The late stage of curated, task-shaped data between pretraining and post-training (OLMo and GLM's name for annealing)."),
"合成数据": ("synthetic data", "Model-generated pretraining text: rephrased documents, textbook-style text, or task-shaped data such as QA and reasoning traces."),
"模型崩溃": ("model collapse", "Degradation from training recursively on a model's own samples; the tails of the distribution vanish first."),
"数据污染": ("data contamination", "Benchmark test items or close variants in the training data, so a score measures memorization."),
"缩放定律": ("scaling laws", "Empirical power laws for loss versus parameters, data and compute, fitted on small runs to size large ones."),
"幂律": ("power law", "A straight line on log-log axes, loss ∝ resource^(−α), valid for N, D or C when the other two are not the bottleneck."),
"不可约损失": ("irreducible loss", "The offset E in Chinchilla's loss: the entropy of text under the data and tokenizer, which no model size can remove."),
"计算最优": ("compute-optimal", "The model size and token count that minimize loss for a given FLOP budget (Chinchilla: about 20 tokens per parameter)."),
"过度训练": ("over-training", "Training well past the compute-optimal token count on purpose, spending training compute to cut serving cost (Llama 3 8B: 15T tokens)."),
"数据受限缩放": ("data-constrained scaling", "Scaling laws when fresh data is finite: repeated tokens are worth less than new ones (Muennighoff et al.)."),
"临界批量大小": ("critical batch size", "The batch size beyond which extra parallelism gives diminishing returns; below it, doubling the batch halves the steps to a target loss."),
"最大更新参数化": ("maximal update parametrization (μP)", "Reparameterizes a network so the best hyperparameters are roughly width-independent: tune a small proxy, then transfer."),
"优化器": ("optimizer", "Turns a minibatch gradient into a parameter update (AdamW for Llama 2 and 3 and DeepSeek LLM, V2 and V3; Muon, the newer alternative for hidden weight matrices, in DeepSeek-V4 and, as MuonClip, Kimi K2)."),
"学习率": ("learning rate", "The step-size multiplier η_t on the update."),
"偏差修正": ("bias correction", "Dividing Adam's moment estimates by 1 − β^t to undo their bias toward zero early in training."),
"学习率调度": ("learning-rate schedule", "Up to three phases (warmup, a hold at the peak, a decay); the choice decides whether a run can be continued or reused."),
"余弦退火": ("cosine decay", "Decay of the learning rate along a half cosine to a floor after warmup."),
"批量大小": ("batch size", "For LLMs, the tokens per optimizer step (sequences × context length); it has grown from about 1M to about 100M tokens."),
"梯度噪声尺度": ("gradient noise scale", "The ratio of gradient noise to signal; it sets the critical batch size in McCandlish et al.'s model."),
"正交化": ("orthogonalization", "Muon's update: replace the gradient matrix by its nearest orthogonal factor (all singular values set to 1), the best unit step under the spectral norm."),
"牛顿-舒尔茨迭代": ("Newton-Schulz iteration", "A matmul-only iteration that approximates orthogonalization, replacing a per-step SVD."),
"显存": ("GPU memory", "The memory on the GPU (HBM); a training step fills it with four kinds of data: model states, activations, temporary buffers and fragmentation."),
"混合精度训练": ("mixed-precision training", "Forward and backward in a 16-bit format with an fp32 master copy for the update; ZeRO counts 2N + 2N + KN bytes with K = 12 for Adam."),
"序列并行": ("sequence parallelism", "Shards the layer-norm, dropout and block-input regions that tensor parallelism replicates along the sequence, dividing those activations by t."),
"激活重计算": ("activation recomputation", "(Gradient checkpointing.) Trade FLOPs for memory: keep some tensors and rerun part of the forward pass inside the backward pass; FlashAttention recomputes its tiles the same way."),
"损失缩放": ("loss scaling", "Multiply the loss by S before backpropagation so small fp16 gradients stay in range; unscale before clipping and skip the step on inf or NaN."),
"微缩放": ("microscaling (MX)", "Block formats in which k = 32 elements share one 8-bit power-of-two scale (MXFP8, MXFP6, MXFP4, MXINT8); MXFP4 costs 4.25 bits per element."),
"集合通信": ("collective communication", "An operation in which all ranks exchange data together: all-reduce, reduce-scatter, all-gather and all-to-all."),
"数据并行": ("data parallelism (DP)", "Replicates the model on every GPU, gives each replica a different slice of the batch, and all-reduces the gradients."),
"零冗余优化器": ("ZeRO (Zero Redundancy Optimizer)", "Removes data-parallel redundancy by sharding optimizer states (stage 1), gradients (stage 2) and parameters (stage 3) across ranks."),
"完全分片数据并行": ("fully sharded data parallel (FSDP)", "PyTorch's implementation of the ZeRO-3 idea: parameters, gradients and optimizer states sharded across data-parallel ranks."),
"流水线并行": ("pipeline parallelism (PP)", "Cuts the layers into p contiguous stages, one per GPU group, passing activations point to point; with m micro-batches the bubble is (p−1)/m of the ideal step time."),
"流式多处理器": ("streaming multiprocessor (SM)", "The GPU's compute unit (132 on an H100 SXM); it keeps many threads resident and hides memory latency by switching between them."),
"线程束": ("warp", "A group of 32 threads that execute together."),
"线程块": ("thread block (CTA)", "A group of warps that lives on one SM and shares its shared memory."),
"核函数": ("kernel", "A function launched on the GPU as a grid of thread blocks."),
"张量核心": ("tensor core", "The matrix-multiply units inside each SM (four per SM, 528 on an H100 SXM)."),
"共享内存": ("shared memory", "Fast on-chip SRAM inside an SM (up to 228 KB on an H100), shared by a thread block; where tiled kernels keep their tiles."),
"算子融合": ("kernel fusion", "Replace n memory round trips of a chain of elementwise ops by one: load once, apply the chain in registers, store once. It cuts traffic, not FLOPs."),
"推理优化": ("inference optimization", "Techniques that shrink one term of the decode cost (weight bytes plus KV bytes over HBM bandwidth) or keep the batch full without breaking a latency promise."),
"服务等级目标": ("service-level objective (SLO)", "A latency promise such as p90 TTFT of at most 0.25 s and p90 TPOT of at most 0.1 s."),
"有效吞吐": ("goodput", "The highest request rate a deployment sustains while a target fraction (say 90%) of requests meets the SLO, per GPU provisioned."),
"分页注意力": ("PagedAttention", "Splits the KV cache into fixed-size blocks (16 tokens by default in vLLM) allocated on demand and found through a block table, like virtual memory."),
"预填充-解码分离": ("prefill-decode disaggregation", "Gives prefill and decode separate GPU pools and ships the KV cache from the prefill instance to the decode instance."),
"量化": ("quantization", "Storing weights, activations or the KV cache in fewer bits; a scheme is named WxAy plus a KV format."),
"训练后量化": ("post-training quantization (PTQ)", "Converts a trained model with a small calibration set (GPTQ, AWQ, SmoothQuant)."),
"量化感知训练": ("quantization-aware training (QAT)", "Trains or fine-tunes with the quantizer in the loop; how Gemma 4 ships quantized checkpoints and DeepSeek-V4 obtains FP4 experts."),
"投机解码": ("speculative decoding", "A cheap draft distribution q proposes γ tokens, the target p scores them in one pass, and an acceptance rule keeps a prefix, leaving the output distribution exactly p."),
"草稿模型": ("draft model", "The cheap distribution q that proposes tokens in speculative decoding."),
"评测": ("evaluation", "Estimating model quality by running it on benchmarks; the headline number is an expectation over choices (prompt, format, sampling, metric) that it hides."),
"基准": ("benchmark", "A fixed set of tasks with a metric, used to compare models."),
"饱和": ("saturation", "Scores bunching below the ceiling (frontier models at 86% to 87% on MMLU), so gaps fall inside noise and label errors."),
"完形填空": ("cloze formulation (CF)", "Score each candidate answer as a continuation of the question and pick the most likely one; the alternative is multiple-choice format (MCF) with lettered options."),
"长度归一化": ("length normalization", "A correction for CF scoring, whose summed log-probabilities penalize longer candidates (OLMES lists four options)."),
"无偏估计": ("unbiased estimator (pass@k)", "Draw n ≥ k samples, count the c that pass, and estimate pass@k = 1 − C(n−c, k)/C(n, k) (Chen et al.)."),
"自洽性": ("self-consistency (majority vote)", "Sample k reasoning paths and return the most common final answer (cons@k); it needs no checker."),
"标准误": ("standard error", "The sampling uncertainty of a score: for accuracy p̂ on n independent questions, √(p̂(1−p̂)/n)."),
"置信区间": ("confidence interval", "For an eval score, p̂ ± 1.96 standard errors gives a 95% interval."),
# ---- Part IV
"指令微调": ("instruction tuning", "SFT on data whose prompts are instructions; in practice the two terms are used interchangeably."),
"行为克隆": ("behavior cloning", "Learning a demonstrator's conditional distribution and nothing else; what SFT does."),
"序列打包": ("sequence packing", "Concatenating several examples into one row up to the maximum length, with attention masked across example boundaries, to avoid padding waste."),
"知识蒸馏": ("knowledge distillation", "Training a student to reproduce a teacher's behavior; two choices: on which sequences (fixed text, teacher samples, student samples) and which signal (full distribution or sampled tokens)."),
"拒绝采样微调": ("rejection-sampling fine-tuning (RFT)", "Sample several responses per prompt, keep those that pass a verifier or score highest under a reward model, and fine-tune on the survivors (best-of-n SFT)."),
"全参数微调": ("full fine-tuning", "Updates every weight; about 16 bytes per parameter with mixed-precision AdamW, before activations."),
"参数高效微调": ("parameter-efficient fine-tuning (PEFT)", "Freeze the pretrained weights and train a small set of new or selected parameters, so gradients and optimizer states exist only for them."),
"低秩适配": ("low-rank adaptation (LoRA)", "Learn a rank-r update (α/r)BA beside a frozen W₀; it can be merged into W₀, so serving costs nothing extra."),
"内在维度": ("intrinsic dimension", "The smallest random-subspace dimension d that reaches 90% of full fine-tuning performance (Aghajanyan et al.); small values motivate LoRA."),
"权重合并": ("weight merging (LoRA)", "Compute W = W₀ + (α/r)BA once and serve the ordinary model with no added latency."),
"分块量化": ("block-wise quantization", "Quantize in small blocks (QLoRA: 64 weights) with one absmax constant each, so an outlier hurts only its neighbors."),
"双重量化": ("double quantization", "Quantize the block scale constants themselves (8-bit, in groups of 256) to cut the per-weight overhead."),
"分页优化器": ("paged optimizers", "Optimizer state is evicted to CPU RAM (unified memory) when the GPU runs out of memory, to survive transient spikes."),
"适配器": ("adapters", "Small bottleneck modules inserted in each Transformer layer (down-project, nonlinearity, up-project, skip connection); they cannot be merged, so they add latency."),
"前缀微调": ("prefix tuning", "Prepends trainable key/value vectors at every layer."),
"提示微调": ("prompt tuning", "Trains soft token embeddings at the input only; it matches full tuning only at large scale."),
"灾难性遗忘": ("catastrophic forgetting", "Loss of pretrained capabilities after fine-tuning; LoRA's \"intruder dimensions\" are one reported cause."),
"偏好优化": ("preference optimization", "Training on (prompt, chosen, rejected) triples so the model learns that one response is better than another."),
"奖励模型": ("reward model (RM)", "Maps a prompt and a response to a scalar that should be higher for responses people prefer; trained with the Bradley-Terry model."),
"布拉德利-特里模型": ("Bradley-Terry model", "The probability that y₁ beats y₂ is σ(r₁ − r₂): it depends only on the gap between latent strengths."),
"古德哈特定律": ("Goodhart's law", "When a measure becomes a target, it ceases to be a good measure; the root of reward over-optimization."),
"奖励过优化": ("reward over-optimization", "The proxy reward keeps rising while true quality peaks and then declines, often with longer, more repetitive responses."),
"配分函数": ("partition function", "Z(x), the normalizer of the KL-optimal policy; intractable, but it cancels in DPO's reward difference."),
"直接偏好优化": ("direct preference optimization (DPO)", "Solves the KL-regularized RLHF objective for the reward in terms of the policy, substitutes it into Bradley-Terry, and gets a classification loss on preference pairs with no separate reward model or RL loop."),
# ---- Part V
"强化学习": ("reinforcement learning (RL)", "An agent picks actions, observes rewards and improves a policy to maximize expected return; a language model already is such a policy."),
"策略": ("policy", "A distribution over actions given a state; for a language model, π_θ(next token | prefix)."),
"评论家": ("critic", "A learned value function V_φ(s_t): a scalar head that predicts expected future reward from each prefix (PPO)."),
"策略梯度": ("policy gradient", "The identity ∇J = E[R · ∇log π(y | x)] (the log-derivative trick), which lets us ascend expected reward without differentiating through sampling or the reward; reward-to-go and a baseline turn R into a per-token advantage A_t."),
"基线": ("baseline", "A quantity subtracted from the return to cut variance without biasing the gradient, as long as it does not depend on the action."),
"价值函数": ("value function", "V(s) = E[G_t | s_t], the expected return from a state; the default baseline."),
"优势函数": ("advantage", "How much better a token is than the policy's average token in that state; zero mean by construction."),
"演员-评论家": ("actor-critic", "The policy is the actor and a learned value model the critic, which replaces the noisy return with a few real rewards plus a prediction."),
"时序差分残差": ("TD residual", "δ_t = r_t + γV(s_{t+1}) − V(s_t), the building block of GAE."),
"广义优势估计": ("generalized advantage estimation (GAE)", "A geometrically weighted (λ) average of multi-step TD advantages, trading bias for variance."),
"重要性采样": ("importance sampling", "Reweight samples from π_old by the ratio ρ = π_θ/π_old to estimate expectations under π_θ."),
"信任区域": ("trust region", "A bound on how far one update may move the policy; the safe step shrinks with response length."),
"近端策略优化": ("proximal policy optimization (PPO)", "Actor-critic policy-gradient algorithm that reuses each batch for several updates by clipping the probability ratio inside the objective, min(ρA, clip(ρ, 1−ε, 1+ε)A); in RLHF a KL penalty keeps the policy near the reference."),
"对齐税": ("alignment tax", "Capability lost on public benchmarks after RLHF (InstructGPT: SQuAD v2, DROP, HellaSwag, WMT15 Fr→En)."),
"奖励黑客": ("reward hacking", "Raising the reward without raising the quality the reward was meant to measure."),
"谄媚": ("sycophancy", "Tailoring answers to the user's stated beliefs instead of the truth; documented in production assistants, and raised by RL although it also exists before RL (Sharma et al.)."),
"模式坍塌": ("mode collapse", "Loss of output diversity after RLHF, including diversity across different inputs."),
"宪法式 AI": ("Constitutional AI", "Anthropic's recipe in which AI feedback guided by a written set of principles supplies the harmlessness labels."),
"基于AI反馈的强化学习": ("reinforcement learning from AI feedback (RLAIF)", "RLHF with preference labels from a strong model instead of humans (Lee et al., Google)."),
"结果奖励模型": ("outcome reward model (ORM)", "Predicts whether the final answer is correct: one label per solution."),
"过程奖励模型": ("process reward model (PRM)", "Predicts whether each reasoning step is correct: one label per step."),
"评分标准": ("rubric", "Written criteria against which an LLM judge scores a response, for tasks without a checkable answer."),
"生成式奖励模型": ("generative reward model (GRM)", "An LLM that judges responses against rubrics in text rather than through a scalar head."),
"可验证奖励强化学习": ("reinforcement learning with verifiable rewards (RLVR)", "RL in which a program (an answer checker, unit tests) replaces the learned reward model; the term comes from Tülu 3."),
"思维链": ("chain of thought (CoT)", "The intermediate reasoning text a model writes before its answer; RLVR at scale makes it long, with reflection and verification."),
"组相对策略优化": ("group relative policy optimization (GRPO)", "PPO without a critic: sample a group of responses per prompt and use the group's mean reward as the baseline, scaled by the group's standard deviation (DeepSeekMath)."),
"冷启动": ("cold start", "A small SFT stage on long chains of thought before RL (R1: thousands of examples), mainly for readable, first-person, language-consistent output rather than for reasoning strength."),
"拒绝采样": ("rejection sampling", "Sample from a checkpoint, keep the responses that pass a check, and reuse them as SFT data (R1: about 600K reasoning and 200K non-reasoning samples)."),
"熵坍缩": ("entropy collapse", "The policy's entropy falling toward zero early in RL, which ends exploration; over 95% of the drop happens early (Cui et al.)."),
"过度思考": ("overthinking", "Responses growing longer than needed during RL, raising cost without matching accuracy gains; length rewards counter it (Kimi k1.5)."),
"课程学习": ("curriculum learning", "Ordering or sampling prompts from easier to harder or by tracked success rate (Kimi k1.5: probability proportional to 1 − s_i)."),
"测试时扩展": ("test-time scaling", "Buying accuracy with inference tokens: sequential (longer chains, self-revision) or parallel (majority vote, verifier)."),
"推理引擎": ("inference engine", "The vLLM- or SGLang-style rollout server (continuous batching, paged KV cache) that generates samples in RL."),
"长尾": ("long tail", "The heavy tail of response lengths in rollouts: the last 10% of requests can take up to 50% of the rollout time."),
"训推一体": ("colocated placement", "The trainer and the inference engine take turns on the same GPUs, and whichever is idle releases its memory."),
"训推分离": ("disaggregated placement", "The trainer and the inference engines own separate GPU pools, with weights broadcast after each update."),
"权重同步": ("weight synchronization", "Moving every parameter from the trainer's sharding layout to the inference engine's after each update."),
"异步训练": ("asynchronous training", "Removes the barrier between generation and training: rollouts continue with older weights while the trainer updates (AReaL)."),
"训推不一致": ("training-inference mismatch", "Different kernels, reduction orders, precisions or sampling rules give different token probabilities in trainer and engine; a common cause of RL collapse."),
"智能体": ("agent", "Acts through tool calls in an environment over many turns until a final answer or a budget runs out."),
"工具调用": ("tool call", "An action the model emits (function name and arguments) that the environment executes and returns as text."),
# ---- Part VI
"推测解码_dummy": None,
"细粒度量化": ("fine-grained quantization", "DeepSeek-V3's FP8 scheme that confines each outlier to a small group: one scale per 1×128 tile for activations, per 128×128 block for weights."),
"累加精度": ("accumulation precision", "The precision of the running sums in an FP8 matmul; H800 tensor cores keep only about 14 bits, so V3 promotes partial sums every 128 elements."),
"冗余专家": ("redundant experts", "Duplicates of hot experts, chosen from online load statistics and re-placed periodically, that balance serving load without extra cross-node traffic."),
"混合推理": ("hybrid reasoning (hybrid thinking)", "Thinking and non-thinking modes in one set of weights, selected by the chat template (DeepSeek-V3.1, GLM-4.5)."),
"闪电索引器": ("lightning indexer", "DSA's cheap scorer I_{t,s} = Σ_j w_{t,j} ReLU(q_{t,j}·k_s); a top-k selector (k = 2048) then limits core attention to those entries."),
"条件记忆": ("conditional memory", "Engram's counterpart to conditional computation: a hashed n-gram embedding table with O(1) lookup that relieves early layers of rebuilding static patterns."),
"早期融合": ("early fusion", "Text and vision tokens enter one backbone from the start and are pretrained jointly (Llama 4)."),
"思考模式": ("thinking mode", "The long-chain-of-thought operating mode, switchable against a non-thinking mode in the same checkpoint (Qwen3)."),
"负载均衡损失": ("load-balancing loss", "The auxiliary loss α·n_r·Σ f_i P_i (f_i: fraction of assignments sent to expert i, P_i: its mean router probability), smallest when routing is uniform; Qwen3 writes n_r as E and computes it over the global batch instead of per micro-batch."),
"思考预算": ("thinking budget", "A cap on thinking tokens enforced outside the model, not learned; accuracy rises smoothly with it (Qwen3)."),
"门控注意力": ("gated attention", "Multiply each head's attention output, before W_O, by an elementwise sigmoid gate computed from the layer input (Qwen's winner among 30 variants)."),
"滚动缓冲区缓存": ("rolling buffer cache", "A KV buffer of fixed size W per layer where position i overwrites slot i mod W; Mistral 7B's 8× memory saving at 32K."),
"局部注意力 / 全局注意力": ("local/global attention alternation", "Alternating sliding-window (local) layers with full-attention (global) layers, for example Gemma 2 in every other layer with window 4,096."),
"注意力汇聚": ("attention sink", "A token, or a learned per-head logit, that absorbs attention mass when a head has nothing to attend to (gpt-oss: one scalar z per head)."),
"全开源": ("fully open", "Releasing weights, training data, code, recipes, logs and intermediate checkpoints (OLMo 2, Olmo 3)."),
"权重平均": ("weight averaging (souping)", "Merging checkpoints or seeds by averaging their weights (OLMo 2's souping of anneals)."),
"剪枝": ("pruning", "Removing weights or layers from a large model; followed by distillation it derives smaller models from one big run (Llama 3.2 1B and 3B, Nemotron-H's MiniPuzzle)."),
# ---- Part VII
"屋顶线模型": ("roofline model", "Attainable FLOP/s is the smaller of peak compute and intensity × bandwidth; it shows which resource bounds a kernel."),
"结构化稀疏": ("structured sparsity (2:4)", "Two zeros in every four values: it doubles NVIDIA's headline tensor-core numbers but is almost never used, so the dense peak is half the listed figure."),
"流水线气泡": ("pipeline bubble", "Idle time at the start and end of a pipeline schedule: (p−1)/m of the ideal compute time with m micro-batches, or a fraction (p−1)/(m+p−1) of the whole step."),
}
G.pop("推测解码_dummy", None)

# Light edit: where the first tagged use is only a passing mention, point to the page/section that defines the concept.
# zh -> (page, anchor or None). None means: use the nearest heading before the term's span on that page.
DEFPAGE = {
    "张量并行": ("15", "tp-sp"),
    "键值缓存": ("06", "kv-cache"),
    "路由": ("08", "router"),
    "低秩适配": ("20", "lora-param"),
    "最大更新参数化": ("14", "mup"),
    "基于人类反馈的强化学习": ("23", "instructgpt"),
    "宪法式 AI": ("23", "cai"),
    "基于AI反馈的强化学习": ("23", "rlaif-vs-rlhf"),
    "负载均衡损失": ("08", "switch-loss"),
    "缩放定律": ("13", "power-laws"),
    "滑动窗口注意力": ("09", "local"),
    "大海捞针": ("10", "niah"),
    "梯度裁剪": ("14", None),
    "学习率预热": ("14", None),
    "权重衰减": ("14", "wd-role"),
    "屋顶线模型": ("16", "roofline"),
    "流水线气泡": ("15", "bubble"),
    "注意力汇聚": ("09", "sinks"),
    "门控注意力": ("11", "gated-attention"),
}

# Display form of a Chinese term when the page's own span breaks the STYLE_GUIDE rule (space between Chinese and Latin text).
DISPLAY = {
    "基于AI反馈的强化学习": "基于 AI 反馈的强化学习",
}
