# Data for the Must-read 25 (page 37). URLs are the exact strings from refs.json.
# read/skim are page counts of the recommended sections (from the arXiv PDF), used to compute minutes.
GROUPS = [
    ("A", "Architecture, scaling and the reference recipe",
     "Start here. Seven papers that every later page assumes: the Transformer, rotary positions, the KV-cache trade-off (GQA), the FlashAttention kernel, the two scaling-law papers and one complete dense recipe (Llama 3)."),
    ("B", "Training systems",
     "Two papers whose arithmetic (what is sharded, what is communicated) appears in almost every systems question; the marked sections are short."),
    ("C", "Post-training and reinforcement learning",
     "The line from SFT and RLHF to critic-free RL with verifiable rewards. Read in this order: InstructGPT for the pipeline, PPO for its optimizer, DPO as the offline alternative, then GRPO, R1 and DAPO, which carry PPO's machinery to verifiable rewards at scale."),
    ("D", "The DeepSeek line: MoE, MLA, sparse and compressed attention",
     "Six reports read in release order. V3 is the anchor for the course's worked numbers, and V4 and V4.1-Flash are the current reference for long-context efficiency."),
    ("E", "Long context, hybrids and open frontier models",
     "Context extension, the linear-attention layer that hybrids use, and two open model families that made different choices from DeepSeek."),
]

# (group, url, citation, short, why, supports, read_sections, read_pages, skim_sections, skim_pages, tier)
P = [
 ('A', 'https://arxiv.org/abs/1706.03762', 'Vaswani et al. (2017). Attention Is All You Need.', 'Attention Is All You Need', 'Source of scaled dot-product and multi-head attention, sinusoidal positions and the Post-LN block: every variant on pages 07 to 11 is a change to it.', ['03', '04', '05'], '§3 (model architecture) and the ablation Table 3 in §6.2', 5, '§4 (why self-attention)', 1, 1),
 ('A', 'https://arxiv.org/abs/2104.09864', 'Su et al. (2021). RoFormer: Enhanced Transformer with Rotary Position Embedding.', 'RoFormer (RoPE)', 'The position scheme of the Llama, Qwen, Mistral, DeepSeek and Gemma families: rotate queries and keys so the score depends only on the offset; YaRN and other context extensions modify it.', ['05', '10'], '§3.1 to §3.3 (formulation, the rotation, properties)', 2, '§3.4 (theoretical explanation)', 2, 2),
 ('A', 'https://arxiv.org/abs/2305.13245', 'Ainslie et al. (2023). GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints.', 'GQA', 'Grouped-query attention and the mean-pooling recipe to convert an MHA checkpoint: the default KV-cache reduction in the Llama and Qwen families and the baseline MLA is compared with.', ['07', '29', '30'], '§2 (uptraining, GQA) and §3.3 (ablations)', 2.5, '§3.2 (main results)', 1, 2),
 ('A', 'https://arxiv.org/abs/2205.14135', 'Dao et al. (2022). FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness.', 'FlashAttention', 'Tiling plus online softmax makes exact attention memory-linear and IO-optimal; interviews ask you to derive the online-softmax recurrence and say which HBM traffic disappears.', ['03', '16'], '§2 (hardware and standard attention), §3.1 to §3.2 (algorithm, IO complexity), App. B.3 to B.4 (forward and backward pass)', 5, '§4 (experiments)', 3, 1),
 ('A', 'https://arxiv.org/abs/2001.08361', 'Kaplan et al. (2020). Scaling Laws for Neural Language Models.', 'Kaplan et al. scaling laws', 'Origin of power-law scaling, the cost of about \\(6N\\) FLOPs per token (so \\(C \\approx 6ND\\)) and the critical batch size, and the baseline Chinchilla corrected: expect "why did they disagree?"', ['04', '13', '34'], '§1 (summary of the laws), §2.1 (parameter and FLOP counts), §6 (optimal allocation of compute)', 8, '§3 and §4 (figures)', 4, 2),
 ('A', 'https://arxiv.org/abs/2203.15556', 'Hoffmann et al. (2022). Training Compute-Optimal Large Language Models.', 'Chinchilla', 'The IsoFLOP method and the rule of about 20 tokens per parameter, the yardstick for any "why so many tokens?" answer; read it with the replications on page 13 before trusting its constants.', ['13', '29', '34'], '§3 (three estimation approaches), §5 (discussion), App. D.4 (comparison with Kaplan)', 6, '§4 (the Chinchilla model)', 2, 1),
 ('A', 'https://arxiv.org/abs/2407.21783', 'Llama Team (2024). The Llama 3 Herd of Models.', 'Llama 3', 'The fullest public account of a dense frontier pipeline: data, an IsoFLOP study, 4D parallelism with an MFU table, staged long-context extension, then SFT, rejection sampling and DPO.', ['04', '12', '13', '15', '29', '33', '34'], '§3.1 to §3.2 (data, architecture, scaling laws), §3.3.2 (parallelism), §3.4 (recipe), §4.1 (post-training modeling)', 9, '§3.3.4 (reliability and failure statistics)', 2, 1),
 ('B', 'https://arxiv.org/abs/1909.08053', 'Shoeybi et al. (2019). Megatron-LM: Training Multi-Billion Parameter Language Models Using Model Parallelism.', 'Megatron-LM', 'Tensor parallelism in three pages: column- then row-parallel matrices, with two all-reduces per layer in the forward pass and two in the backward pass.', ['15'], '§2.3 (data and model parallelism), §3 (model parallel transformers), §5.1 (scaling analysis)', 3.5, '§5.2 (GPT-2 results)', 0.5, 2),
 ('B', 'https://arxiv.org/abs/1910.02054', 'Rajbhandari et al. (2020). ZeRO: Memory Optimizations Toward Training Trillion Parameter Models.', 'ZeRO', 'The \\(2N + 2N + KN\\) memory accounting (\\(K = 12\\) for mixed-precision Adam) and the three sharding stages: the arithmetic behind FSDP and every "will it fit" question.', ['15', '34'], '§3 (where did the memory go), §4 to §5 (ZeRO-DP stages), §7 (communication analysis)', 7.5, '§10 (evaluation)', 3, 1),
 ('C', 'https://arxiv.org/abs/2203.02155', 'Ouyang et al. (2022). Training language models to follow instructions with human feedback.', 'InstructGPT', 'The SFT, reward-model and PPO pipeline that later recipes modify, with its numbers: dataset sizes, PPO-ptx, the alignment tax, and a 1.3B model preferred to the 175B GPT-3.', ['21', '22', '23', '19'], '§3.2 (dataset sizes), §3.4 to §3.5 (human data, models), App. C.1 to C.4 (SFT, RM and RLHF training details)', 6, '§4.1 to §4.2 (results)', 4, 1),
 ('C', 'https://arxiv.org/abs/1707.06347', 'Schulman et al. (2017). Proximal Policy Optimization Algorithms.', 'PPO', 'The clipped surrogate objective in 8 pages: write it from memory and say what the clip does for positive and negative advantages; GRPO and DAPO edit it.', ['22', '23'], '§2 to §5 (background, clipped objective, adaptive KL, algorithm)', 3, '§6.1 (comparison of surrogate objectives)', 1, 1),
 ('C', 'https://arxiv.org/abs/2305.18290', 'Rafailov et al. (2023). Direct Preference Optimization: Your Language Model is Secretly a Reward Model.', 'DPO', 'The closed-form KL-regularized optimum turned into a classification loss on preference pairs: re-derive it on a whiteboard, and know what it leaves open: the paper asks about out-of-distribution generalization and over-optimization, while offline data and likelihood displacement (page 21) came from later work.', ['21'], '§4 to §5 (the objective and its analysis), App. A.1 to A.4 (derivations and gradient)', 5, '§6.1 (how well does DPO optimize the RLHF objective)', 1, 1),
 ('C', 'https://arxiv.org/abs/2402.03300', 'Shao et al. (2024). DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models.', 'DeepSeekMath (GRPO)', 'Origin of GRPO (PPO without a critic, group-mean baseline); §5.2 casts SFT, RFT, DPO, PPO and GRPO as one gradient with different data and weights.', ['24', '26', '22'], '§4.1 (GRPO), §5.2 (insights of reinforcement learning)', 8, '§2.1 (math corpus collection)', 2, 1),
 ('C', 'https://arxiv.org/abs/2501.12948', 'DeepSeek-AI (2025). DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning.', 'DeepSeek-R1', 'R1-Zero shows reasoning emerging from outcome-reward RL alone; R1 adds a cold start, a second RL stage and rejection-sampling SFT. Read the arXiv v2 text (January 2026): some numbers differ from v1.', ['24', '28', '19'], '§2 (R1-Zero), §3 (R1 pipeline), App. A.3 (GRPO versus PPO), App. F.1 and G.2 (distillation versus RL, unsuccessful attempts)', 10.5, 'App. B.4 (hyperparameters)', 1, 2),
 ('C', 'https://arxiv.org/abs/2503.14476', 'Yu et al. (2025). DAPO: An Open-Source LLM Reinforcement Learning System at Scale.', 'DAPO', 'Four fixes to GRPO at scale (clip-higher, dynamic sampling, token-level loss, overlong reward shaping) with a cumulative ablation: the checklist for "why did the RL run collapse?"', ['24'], '§3 (the four techniques), §4.3 (training dynamics)', 4, '§2 (preliminaries)', 2, 2),
 ('D', 'https://arxiv.org/abs/2401.06066', 'Dai et al. (2024). DeepSeekMoE: Towards Ultimate Expert Specialization in Mixture-of-Experts Language Models.', 'DeepSeekMoE', 'Fine-grained expert segmentation plus shared experts, the MoE design that V2 and V3 scale up and Kimi K2 keeps (Qwen3 keeps the fine-grained experts but drops the shared one); its §4 ablations are the evidence interviewers ask about.', ['08', '26'], '§3 (architecture), §4.4 (ablations)', 4, '§4.5 (expert specialization analysis)', 3, 2),
 ('D', 'https://arxiv.org/abs/2405.04434', 'DeepSeek-AI (2024). DeepSeek-V2: A Strong, Economical, and Efficient Mixture-of-Experts Language Model.', 'DeepSeek-V2', 'Multi-head latent attention (a latent KV cache with decoupled RoPE) and device-limited routing; its 93.3% KV-cache reduction is against dense DeepSeek 67B, not an isolated MLA ablation (page 07).', ['07', '26', '27'], '§2.1 (MLA), §2.2 (DeepSeekMoE, device-limited routing), App. C (full MLA formulas)', 7, '§3.2.3 (efficiency claims)', 1, 1),
 ('D', 'https://arxiv.org/abs/2412.19437', 'DeepSeek-AI (2024). DeepSeek-V3 Technical Report.', 'DeepSeek-V3', "The anchor for the course's worked numbers: MLA, a 256-expert MoE with auxiliary-loss-free balancing, multi-token prediction, DualPipe and FP8 training, plus the cost accounting.", ['07', '08', '11', '15', '27', '33', '34'], '§2 (architecture, MTP), §3.2.1 (DualPipe), §3.3 (FP8 training)', 10, '§4.2 to §4.3 (hyperparameters, long-context extension)', 1.5, 1),
 ('D', 'https://arxiv.org/abs/2512.02556', 'DeepSeek-AI (2025). DeepSeek-V3.2: Pushing the Frontier of Open Large Language Models.', 'DeepSeek-V3.2', 'DeepSeek Sparse Attention (a lightning indexer selects the top-k keys; added to V3.1-Terminus by continued training) and the four stabilizers for scaling GRPO; only 17 pages of main text.', ['09', '24', '25', '28'], '§2 (DSA, parity evaluation, inference cost), §3.1 (scaling GRPO)', 5, '§3.2 (thinking in tool use)', 4, 2),
 ('D', 'https://arxiv.org/abs/2606.19348', 'DeepSeek-AI (2026). DeepSeek-V4: Towards Highly Efficient Million-Token Context Intelligence.', 'DeepSeek-V4', "The course's most-cited source (an April 2026 preview report): CSA and HCA compressed attention for 1M tokens (abstract: at 1M tokens V4-Pro needs 27% of V3.2's single-token inference FLOPs and 10% of its KV cache), mHC, Muon and on-policy distillation.", ['07', '09', '14', '19', '28', '33'], '§2.2 (mHC), §2.3 (CSA and HCA), §2.4 (Muon), §3.5.1 (KV cache structure), §5.1.2 (on-policy distillation)', 10, '§4.2.3 (mitigating training instability)', 1, 1),
 ('D', 'https://arxiv.org/abs/2609.19969', 'DeepSeek-AI (2026). DeepSeek-V4.1-Flash: Pushing the Limits of KV Cache Compression.', 'DeepSeek-V4.1-Flash', 'The newest KV-compression design (September 2026): cross-layer KV and index reuse (CSA2), an FP4 main KV cache (890 bytes per token in HBM, per the abstract) and SWA bounded replay; closest to your research, so read it after V4.', ['07', '28', '09'], '§2.2 to §2.3 (causal encoder-decoder, CSA2), §2.4.4 (FP4 KV cache), §3.2 (inference system)', 5.5, '§2.4.2 to §2.4.3 (Engram, DSpark)', 1.5, 3),
 ('E', 'https://arxiv.org/abs/2309.00071', 'Peng, Quesnelle, Fan, Shippole (2023). YaRN: Efficient Context Window Extension of Large Language Models.', 'YaRN', 'The RoPE extension recipe (frequency-dependent interpolation, NTK-by-parts, plus an attention temperature) that DeepSeek-V3 uses from 4K to 128K; read it with the reference code.', ['10'], '§2.1 (RoPE), §3 (methodology)', 4, '§4 (experiments)', 3, 2),
 ('E', 'https://arxiv.org/abs/2412.06464', 'Yang et al. (2024). Gated Delta Networks: Improving Mamba2 with Delta Rule.', 'Gated DeltaNet', "The gated delta rule: Mamba-style decay (fast erasure) plus the delta-rule update (targeted overwrite), the layer in Qwen3-Next's 3:1 hybrid. Chosen for your long-context research.", ['09', '30'], '§2 (preliminaries), §3 (gated delta rule, S-NIAH case study, chunkwise algorithm, hybrids)', 4.5, '§4 (experiments)', 3, 3),
 ('E', 'https://arxiv.org/abs/2505.09388', 'Qwen Team (2025). Qwen3 Technical Report.', 'Qwen3', 'A full open family (0.6B dense to 235B-A22B MoE): QK-norm, global-batch load balancing, three-stage pretraining, and post-training that fuses thinking and non-thinking modes and distills strong to weak.', ['19', '30', '33'], '§2 (architecture), §3.1 to §3.2 (data, pretraining stages), §4.1 to §4.5 (post-training)', 5.5, '§4.7 (discussion)', 1, 3),
 ('E', 'https://arxiv.org/abs/2507.20534', 'Kimi Team (2025). Kimi K2: Open Agentic Intelligence.', 'Kimi K2', 'MuonClip (Muon plus QK-Clip), a sparser MoE than V3 (384 experts, 8 active), and the agentic data synthesis and RL infrastructure; shows what an independent team kept from V3 and what it changed.', ['11', '14', '25', '27', '32', '33'], '§2.1 (MuonClip), §2.3 (model architecture), §3.2.3 and §3.3 (RL algorithm and infrastructure)', 5, '§3.1.1 (agentic data synthesis)', 2, 3),
]
MUST_URLS = [p[1] for p in P]

def minutes(read, skim):
    m = 4 * read + 1.5 * skim
    return int(5 * int(m / 5 + 0.5))
