#!/usr/bin/env python3
"""Generate assets/question_bank.js: every interview question from the finished pages.

Usage:
    python3 tools/build_bank.py                 # write assets/question_bank.js
    python3 tools/build_bank.py OUT.js          # write elsewhere (the site build uses this)
    python3 tools/build_bank.py --check         # exit 1 if the committed file is stale

Page 36 renders the bank from this file, so a fix to a question on its source page reaches the
bank the next time this runs (the site build runs it on every deploy). Only pages whose manifest
status is "written" are included, and the aggregate pages (36, 37) are skipped.
"""
from __future__ import annotations

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import manifest  # noqa: E402

ROOT = manifest.ROOT
SKIP = {"36", "37"}
DEFAULT_OUT = os.path.join(ROOT, "assets", "question_bank.js")


def qa_blocks(src: str):
    """Yield (tier, inner_html) for each top-level <details class="qa" ...> block."""
    pos = 0
    open_re = re.compile(r'<details class="qa" data-tier="(\w+)"[^>]*>')
    while True:
        m = open_re.search(src, pos)
        if not m:
            return
        depth, i = 1, m.end()
        tag = re.compile(r"<(/?)details\b")
        while depth:
            t = tag.search(src, i)
            if not t:
                return
            depth += -1 if t.group(1) else 1
            i = t.end()
        close = src.rfind("</details", m.end(), i)
        yield m.group(1), src[m.end():close]
        pos = i


def clean(fragment: str, slug: str) -> str:
    fragment = re.sub(r'\sid="[^"]*"', "", fragment)                      # ids would collide on page 36
    fragment = re.sub(r'href="#', f'href="{slug}.html#', fragment)         # in-page anchors point home
    return fragment.strip()


def collect() -> list[dict]:
    out = []
    for part in manifest.load()["parts"]:
        for p in part["pages"]:
            if p["status"] != "written" or p["n"] in SKIP:
                continue
            path = os.path.join(ROOT, "pages", p["slug"] + ".html")
            src = open(path, encoding="utf-8").read()
            for k, (tier, inner) in enumerate(qa_blocks(src)):
                m = re.search(r"<summary>([\s\S]*?)</summary>", inner)
                if not m:
                    continue
                q = re.sub(r'<span class="tier">[^<]*</span>\s*', "", m.group(1))
                a = inner[m.end():]
                out.append({
                    "id": f'{p["n"]}-{k + 1}',
                    "page": p["n"], "slug": p["slug"], "title": p["title"],
                    "part": part.get("title", ""), "tier": tier,
                    "q": clean(q, p["slug"]), "a": clean(a, p["slug"]),
                })
    return out


def render(questions: list[dict]) -> str:
    body = json.dumps(questions, ensure_ascii=False, separators=(",", ":"))
    return ("// Generated by tools/build_bank.py from the finished pages. Do not edit by hand.\n"
            f"window.LLM_QBANK = {body};\n")


def main() -> int:
    args = sys.argv[1:]
    text = render(collect())
    if args and args[0] == "--check":
        cur = open(DEFAULT_OUT, encoding="utf-8").read() if os.path.exists(DEFAULT_OUT) else ""
        if cur != text:
            print("assets/question_bank.js is stale: run python3 tools/build_bank.py")
            return 1
        print("question bank up to date")
        return 0
    out = args[0] if args else DEFAULT_OUT
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8").write(text)
    n = text.count('"id":')
    print(f"wrote {os.path.relpath(out, ROOT) if out.startswith(ROOT) else out}: {n} questions, {len(text) // 1024} KiB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
